### ISSUE TITLE
Verifiable ordering of transactions via validator consensus

### ISSUE THREAD

**Issue by HarryR** [barryWhiteHat/roll_up#17]
There was a model proposed, similar to Casper, where one validator is chosen to decide which transactions are included in a specific block, then the remaining validators confirm data availability for that block.

## Approach 1

That process is:

 * RNG selects 1 of N validators as the 'choose which transactions are included in the next block'
 * That selected validator compiles all the transactions, puts them in a content-addressable block
 * Publishes that block (and metadata) to the block-chain as its commitment
 * Other validators confirm the data is available, is valid etc.
 * Majority of validators sign the data, committing to the block
 * Data availability happens?
 * Prover watches for validator commitments, retrieves data and provides zkSNARK proof for that block
 * Prover can only submit a proof which match the validators commitment to the new merkle root

## Approach 2

What I'm proposing is the following:

 * As each transaction is submitted by a user, the validators reach a consensus about which TX to include in the block next
 * The user is provided with a receipt, signed by a majority of the validators, that their transaction will be item number N in the sequence.
  * This receipt contains:
     * The merkle roots of every previous item in the block
     * Previous value
     * Previous merkle path
     * New value
     * This receipt shows the state transition from Merkle root N-1 to N
 * Validators commit to a sequence of Merkle roots as being the next block, this sequence is published on-chain, along with the content addressable hash for the block
 * Data availability happens?
 * Prover can only submit proof where the sequence of transactions applied in-order result in the sequence of merkle roots previously committed to.

So, the interesting differences between the two approaches are that with the second the user gets a receipt for every transaction from the validator consensus, this essentially is finality on a tx-by-tx basis, the information included in this receipt verifies the order of every transaction so far in that block.

If the validators publish a different set of merkle roots on-chain, any user with a receipt signed by a majority of validators can prove that their transaction was excluded from the commitment.

Likewise any user, after receiving a signed receipt for their TX can, upon publishing of the validators commitment, verify that their transaction was not only included in that block, but was included in the agreed order.

This requires the validators to do the following:

 * Agree on a sequence of transactions, one-at-a-time (e.g. a 'live consensus' providing instant finality)
 * The majority of them provide signatures for each transaction
 * Provide proof that they applied that specific transaction in-sequence
 * Their own signatures can be used against them if they later commit to a different block content
 * The prover also proves data availability, as the validators commit to not only the content of the raw content of the block (which must be proven in-circuit), but also the actions of each block being applied (via the merkle root updates)

---------------

More notes:

Philippe Castonguay @PhABC 21:09
tho I'd possibly increase it to RNG selects 50% of the validators deterministically to run the same algorithm and come up with the same result. and there must be a consensus with the remaining 50% that the data is consistent and available, or something like that.

That's hard because if using a p2p messaging framerwork, no validators will have the same set of txs.

HaRold @HarryR 21:09
ya it'd be a multi-round common-subset problem, which has way more edge cases
so maybe simpler is best, pick one validator to pick the TXs
the remaining provide proof of data availability?
there are so many edge cases though

Philippe Castonguay @PhABC 21:10
You make each validator provide a deterministically random entry in the tree as part of their signature

That's not bad, but I think that it's not sufficient. If you have a large amount of leaves, it's very likely you could have a few leaves that are unavailable and these would almost never be detected.

Imagine you have 2^32 leaves, you can predict what's the probability that a given leave will be picked for any given round, and know that you can make 1 leaf unavailable and it will take about 1 year before it has a good chance of it being selected. You have plenty of time to leave the validator pool for this.

HaRold @HarryR 21:12
nah, you can't make only one leaf unavailable, the entire block of TXs needs to be published in one block, content addressed
proof of ingesting that block is providing a proof of any leaf, as you must update the merkle tree to reach the same root
if any one transaction isn't processed by a validator the root won't be the same
so, the nominated validator, says 'I picked these TXs, the root is X, the content addressable block (IPFS, or BitTorrent) is Y'

Philippe Castonguay @PhABC 21:14
So, let's clarify something.

As a majority validator can make data unavailable for a few parties ;

Other validators
Users
Prover
Correct?

HaRold @HarryR 21:15
yes, with a majority they can pass the information internally and externally appear to be agreeing on the same information, even though it's unavailable to others

Philippe Castonguay @PhABC 21:16
The ultimate risk is the users not having the data, correct? If the prover doesn't have the data, they can't build a proof. If the majority of the validator dont have the data, they won't sign. In both cases, blocks can't be included. However, if data is unavailable to users, chain is still live, but users don't know what's happening.
Is this correct?

HaRold @HarryR 21:17
so by committing to the data in content-addressable form, you would require that the chosen validator to pick the TX pool was one of your insiders

Philippe Castonguay @PhABC 21:17
Yeah

HaRold @HarryR 21:18
which can either deny data (by passing internally), or scramble it to make it useless externally, but with a majority they can force it through as being the next block

Philippe Castonguay @PhABC 21:18
I'm asking, what happens when validators (majority) and prover collude, how can users challenge this and say "wait a second, we think the system is colluding against the users"

HaRold @HarryR 21:18
hmm

Philippe Castonguay @PhABC 21:19
So far, it seems like we are fine in terms of data availability unless majority of validators and prover collude. Wondering if we can get better with an extra, expensive step.
For instance, the silliest example would be to request validators to rebuild the tree on-chain directly, with all the leaves. If they can't, they get slashed. However, this seems crazy expensive
What i'm asking is ; What do validators have to risk by witholding data? How do they get penalized?

HaRold @HarryR 21:21
I was thinking about sequentially updating the merkle tree in-circuit, where each TX is applied in sequence, with a path and new value which generates a new root, this is required to be in-sequence and in-order
that's how the circuit has to work anyway
could you make the validators commit to the merkle root after each transaction is applied in-order?

Philippe Castonguay @PhABC 21:21
Right, but how many blocks and gas would that take and how can users resort to that option without griefing the validators?

HaRold @HarryR 21:24
so, instead of picking one validator to decide the TXs in the block, for each TX the validators (as a group) must come to a consensus about which TX will be accepted next, then provide a proof signed by all that says 'the merkle roots in sequence so far are this, your TX is this, the root after applying is this'. Where in order for the proof to be accepted it must provide the merkle roots in-sequence (so 1 per TX)
where, as a user, I have a signed commitment that my TX will be included at sequence number N, and all the merkle roots before that are X
then I can show that the validators committed to something which differed from what the prover prooved

Philippe Castonguay @PhABC 21:25
And do the prover pass this signed data on-chain?

HaRold @HarryR 21:26
ideally only a hash of it, a hash of the sequence of merkle roots, to keep it cheap (public inputs are expensive)

Philippe Castonguay @PhABC 21:26
Right, so they can still withold what creates that hash from the users, no?

HaRold @HarryR 21:26
but the validators could commit to a sequence of hashes, in order to commit to the next block
where if you provide an input, which is signed by the validators, for a specific item in the sequence, which doesn't match the preimage
then it's a certified validator fraud
so say the validator commitment phase they agree on sequence of TXs, a majority of validators signs each TX, in-order
each transaction the user submits will get a receipt, which specifies its order and validator signatures
if the validators don't include that in a block, the user can prove their signatures on-chain as proof that they didn't include their TX

Philippe Castonguay @PhABC 21:29
Let me rehash this a bit to be more precise ;

then provide a proof signed by all that says 'the merkle roots in sequence so far are this, your TX is this, the root after applying is this'.

You have such a signed message for each tx / user?

HaRold @HarryR 21:30
I want to avoid a signature for each TX, only a hash of the information for that TX (the leaf value, in-sequence merkle tree update info) - which is verified by the SNARK circuit and not on-chain
but, the validators provide the user a signature, so it's not necessary on-chain
that signature can be used against them on-chain when the validators submit the sequence of TX hashes as a commitment to the next block
in the window between the validators commitment and the next block, users can use the receipt they got from the validators to prove that the validator rescinded on their obligation to include the TX in the block
likewise, because the TX block is content addressable, you can (possibly very expensively) prove that your TX wasn't included in it, even though the validators signed proof that you were
where the block is N*16 bytes long for N transactions

Philippe Castonguay @PhABC 21:36
If the validators withold the data, can't they just not provide these signed commitment in the first place as well?

HaRold @HarryR 21:40
for them to agree to include a users TX, a majority of the validators have to provide the user with their signatures for that TX. so yes, a majority of them can not sign that specific users TX to censor them. but any user who is provided with a receipt has enough information to prove they were included in a specific block
which means, as long as the users hold on to their receipts, they have provable data availability
where any one of the receipts can prove the availability of the data for that one TX, and the block being mined by the prover where at least one receipt is provably a constituent of that block, then at least one person has data availability
hmm this is getting complicated
was thinking about censorship resistance, blind commitments, where you can prove that they excluded something after discovering what it was, but then it becomes a race between the TX submitter, the prover, and network congestion, for the proof to be valid

HaRold @HarryR 21:46
I will write up these notes anyway and dump them in a ticket

Philippe Castonguay @PhABC 21:52
Yeah, thanks Harry, will be good to summarize all this in a ticket.

Philippe Castonguay @PhABC 22:00
I think we will be able to make all this much simpler once ideas are summarized and written down

**Comment by barryWhiteHat** [comment]
@HarryR can we close this as we decided to go another way?
