### ISSUE TITLE
Chain rollback on data unavailability

### ISSUE THREAD

**Issue by barryWhiteHat** [barryWhiteHat/roll_up#19]
If we use so https://github.com/barryWhiteHat/roll_up/issues/18 then we don't have to do plasma exit we can safely  roll back the chain. 

Say we have a list of states.
```
s1 - > s2 -> s3 -> s4 -> s5 
```

Where we start at s1 and end at s5

at s1 data is available and s5 it is not. But we do not know when it became unavailable.
So tell everyone we are going to roll back the state from s5 to s4. Does anybody

    1. Have a leaf that they want to withdraw at the state s5.
    2. Does anyone want to add state and become the new operator at s5.

If we don't get anyone for s5 we withdraw anyone who asked and step the state back to s4 and repeat.

This way we start to go back in time and once an available state appears we will hopefully get a new operator. Or else we just withdraw everyone.

So we can recover without everyone having to move to a new chain. Only the inflight transactions that have their data  available. Everyone else just waits for a new operator. 

_Originally posted by @barryWhiteHat in https://github.com/barryWhiteHat/roll_up/issues/18#issuecomment-422747130_

### request exit
If the operator fails to process requests in the pritoirty que. We will begin to roll back the chain. Allowing users to exit and offering the position of operator in an open auction. 

Firstly we pause the system for a long period of time to allow users to prepare their exit requests. A user can submit an exit request by calling 
`roll_back_exit(uint merkle_tree_address, 
                uint state, 
                bytes32[tree_depth] markle_proof, 
                bytes32 leaf,
                bytes32 authorization_signature
                bytes32 public_key_of_leaf, 
                bytes32 rhs_of_leaf
                )`

1. The contract then validates these requests are valid as in "Example exit using the priority queue"
2. It confirms that that leaf has not been exited.
3. It confirms that that leaf is not already in the exit request. If it is it will use the request with the latest state. 

### bid to be operator 
A user can request to be the new operator by calling 

`
bid_new_operator(
                uint state,
                bytes32[tree_depth] markle_proof, 
                bytes32 leaf
)
`

They pass `state` which is the state that they want to start operating from aswell as a deposit. 

They must also provide a valid proof of knoledge of the data that resulted in the previuos operator being slashed. 

For each request we check weather the their state is newer than the current higest bid and that their bit is higher than the current highest bit. If either is true we add repalce the current highest bidder with them. 

### rolling back
Then we start to roll back the chain. We step back the state to the previous one. We then 

1. Process all exit requests
2. Check if we have a new opeartor 

We continue this until we either have a new operator or roll the state back to state zero.

**Comment by barryWhiteHat** [comment]
> No matter how the new operator is selected, some participants will not want to migrate to her new sidechain (because they don't like / don't trust her). Therefore we can not mass-migrate everybody with stake at older states. Instead, migration should be strictly opt-in. Is this obvious or requires a discussion?

This is not obvious, if we use the Priority que architecture the users who do not wish to be part of the chain can exit and so so cheaper than before. 

They don't need to trust her.

**Comment by gluk64** [comment]
I have a leaf with data from state s1. We are going to roll back the state from s5 to s4. Can I exit before the switch?

**Comment by barryWhiteHat** [comment]
> I have a leaf with data from state s1. We are going to roll back the state from s5 to s4. Can I exit before the switch?

So you have data in s1 and data became unavailable at s2. So two things can happen

1. An operator takes over before we reach s1 and you use priority que to exit or to cause their deposit to be burned and the state to roll back again. 
2. An operator takes over at s1 and you an transfer your coins or exit or use priority que to exit. 
3. No operator takes over and you exit at s1.

**Comment by gluk64** [comment]
Still wouldn't make me quite happy, because I trusted in security parameters **in combination** with the reputation of the original operator.

**Comment by barryWhiteHat** [comment]
> That means that the new sidechain will have to have security parameters (deposit and priority queue throughput) not worse than the original one I trusted. Right?

Yes

> Still wouldn't make me quite happy, because I trusted in security parameters in combination with the reputation of the original operator.

Yes and that is why you support not slashing the operator per priority que requests. and this is why i do. that over time a dossing operator can be removed. But in the worst case this system degrades to an on chain token. No matter who the operator is.
