### ISSUE TITLE
Proposal: 253 bit leaf identifiers

### ISSUE THREAD

**Issue by gluk64** [barryWhiteHat/roll_up#21]
**Proposal**: for nullification checks, let's use a 253 bit unique immutable leaf id stored in the leaf instead of its address.

**Rationale**: it allows to split leaves in-circuit in such a way that allows efficient checks of nullification. This is important in the context of Plasma Debit.

**How it works**: 

When a new leaf is inserted, its id equals its address (padded to 32 bits: bit 0x80000 must be set).

When we want to split it, two new leafs are created with ids appended by a single bit:

```
id(child 1) = id(parent)*2
id(child 2) = id(parent)*2 + 1
```

When the nullified status is checked in `isLeafNullified(uint256 leaf_id)`, checks are required for all parent ids (max. 224 SLOAD operations):

```solidity
var sub_leaf = leaf_id;
while(sub_leaf > 0x800000) { // until we reach prefix length
    checkNullifier(sub_leaf);
    sub_leaf /= 2; // shift one bit right
}
```

**Comment by barryWhiteHat** [comment]
How will this system react to overflows ? 

In a snark we do all our operations %p where `p = 21888242871839275222246405745257275088548364400416034343698204186575808495617`

Where `21888242871839275222246405745257275088548364400416034343698204186575808495616 + 1 = 0`

So its possible that after a number of transfers a leaf will exceed p and wrap around to zero.

**Comment by gluk64** [comment]
No big deal, then an id can be 253 at max.

**Comment by barryWhiteHat** [comment]
What if an attacker overflows their ID so that it matches your parent ID? 

I guess we could add a overflow check. Then you would only be able to split your coin 252 times. Because each double can add a bit to the id(parent) * 2

So then to check for nullification you have to check 
for (i = 0; i < 252 ; i++)
    1. that no leaf id(parent)*2*i has been exited
    2. That no leaf id(parent)/2*i has been exited 

Does that look right ?

**Comment by gluk64** [comment]
> we could add a overflow check

We need to, of course.

> Then you would only be able to split your coin 252 times

Each id will have a prefix of the original leaf. If leaf address is 32 bit, than it can be split 253-24 = 221 times.

> So then to check for nullification you have to check

Simpler, one check for each bit:

```
mask = 0xffffffff; // 32 bits
for (i = 32; i <= 253 ; i++) {
    checkNullifier(leaf_id & mask);
    mask = (mask << 1) | 1;
}
```

**Comment by gluk64** [comment]
Wait, I messed up data formats. Let me rewrite id generation and checks.

**Comment by gluk64** [comment]
Updated last comment the issue description.

**Comment by barryWhiteHat** [comment]
Could you provide an example of deposit , split and withdraw? I think i am starting to understand this but an example would be useful.

**Comment by gluk64** [comment]
I will create a separate issue about Plasma Debit and explain it there.

**Comment by gluk64** [comment]
Oh, this only protects against withdrawals of the parent leaves, but not the child ones... :/

**Comment by gluk64** [comment]
Ok, there is solution:

- In the case of Plasma exit, everyone who had not withdrawn their funds yet is supposed to watch all exit requests (which is the case anyway).
- If they notice a request for a leaf whose parent or child leaf has already exited, they must protest.

The proof of double exit is a trivial bitwise operation in EVM.

Watching is computationally simple ( O(1) memory writes per check ) and requires `4 * total_leaves` bytes memory (max. 8GB, but we can limit it to, say, 1GB, so that everybody can run the software).

**Comment by barryWhiteHat** [comment]
> If they notice a request for a leaf for which a parent or child leaf has already exited, they must protest.

I don't like this it breaks the roll_back property that users don't need to watch the chain until the block that they received their leaf in. Because they need to watch always to make sure that their leafs child or parent does not try to exits.

**Comment by gluk64** [comment]
Agree, it's annoying to break this nice property. Plasma Debit is itself annoying.

I shall reformulate though: not everyone, but somebody must watch. All information will be available from EVM logs, one honest observer is enough.

This is a trade-off to decide on. If leaves can not be split up, the rollback property is preserved, but a lot more onchain activity or extra capital is required during normal operation to rebalance undercapitalized leaves.

**Comment by barryWhiteHat** [comment]
> if we encounter raised flag for a parent leaf, the parent exit request gets cancelled and the requester slashed

Can an attacker make the data of a parent unavailable and then double withdraw it?

**Comment by gluk64** [comment]
> Can an attacker make the data of a parent unavailable and then double withdraw it?

No. All "data" is leaf ID you're requesting to withdraw.
