### ISSUE TITLE
In snark decompression function

### ISSUE THREAD

**Issue by barryWhiteHat** [barryWhiteHat/roll_up#8]
Because input variables are quite expensive to pass to snark verification I would be interested to hear thoughts on a compression function that can be uncompressed inside the snark cheaply.

So you would pass the compressed data and then expand it in snark. Allowing us to compress multiple field elements into fewer elements to reduce the inputs. 

This could let us with our data availability problems https://github.com/barryWhiteHat/roll_up/issues/6

**Comment by HarryR** [comment]
The problem is high-entropy data doesn't compress well... you can't compress uniformly random data...
